#!/usr/bin/env bash

export APP="smso_con"

create_new_session()
{

  cd /home/aleak/lr/SMSO

  tmux new-session -s $APP -n con -d

  tmux send-keys -t $APP:1 'cls ; cd /home/aleak/lr/SMSO ; zeus console'  C-m

}

