#!/usr/bin/env bash
# should be called from tmux_console

export APP="smso_dev"

create_new_session()
{

  cd /home/aleak/lr/SMSO

  tmux new-session -s $APP -n sysmon -d

  tmux send-keys -t $APP:1 'cls ; cd /home/aleak/lr/SMSO ; zeus start' C-m

}

